// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MZwXmlAXHx9G95W3DOgvTPjFqSTxFcM',
    appId: '1:630635158695:web:fdff1a13eabf2726478f82',
    messagingSenderId: '630635158695',
    projectId: 'studentloginbackend-15b3c',
    authDomain: 'studentloginbackend-15b3c.firebaseapp.com',
    storageBucket: 'studentloginbackend-15b3c.firebasestorage.app',
    measurementId: 'G-5LHWTCTSG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOlnVIhDL-MDVCktrDEkauPCaEtLmQ3U',
    appId: '1:630635158695:android:81fe82798016a947478f82',
    messagingSenderId: '630635158695',
    projectId: 'studentloginbackend-15b3c',
    storageBucket: 'studentloginbackend-15b3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEtIn6fzfuuZHrEnihVw7Mf2iISj_fzUw',
    appId: '1:630635158695:ios:90a4f7930c9dd6f0478f82',
    messagingSenderId: '630635158695',
    projectId: 'studentloginbackend-15b3c',
    storageBucket: 'studentloginbackend-15b3c.firebasestorage.app',
    iosBundleId: 'com.example.studentdirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEtIn6fzfuuZHrEnihVw7Mf2iISj_fzUw',
    appId: '1:630635158695:ios:90a4f7930c9dd6f0478f82',
    messagingSenderId: '630635158695',
    projectId: 'studentloginbackend-15b3c',
    storageBucket: 'studentloginbackend-15b3c.firebasestorage.app',
    iosBundleId: 'com.example.studentdirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2MZwXmlAXHx9G95W3DOgvTPjFqSTxFcM',
    appId: '1:630635158695:web:08a0215727bd09d0478f82',
    messagingSenderId: '630635158695',
    projectId: 'studentloginbackend-15b3c',
    authDomain: 'studentloginbackend-15b3c.firebaseapp.com',
    storageBucket: 'studentloginbackend-15b3c.firebasestorage.app',
    measurementId: 'G-4L7JZMZ0C6',
  );
}
